### ISSUE TITLE
[node/js] Doc Subscription

### ISSUE THREAD

**Issue by mattdesl** [n0-computer/iroh-ffi#108]
The API is a bit awkward right now. It blocks everything (sync?) so I can't find an easy way of having it run in the background or just polling it occasionally. 

In the example below, the setBytes function runs correctly, but then when I wait for `getMany` it never returns, due to the subscription function. If I remove the `subscribe()`, it can query successfully.

```js
console.log("Listening...");
listen();

const key = Buffer.from("foo");
console.log("Setting bytes");
doc.setBytes(author, key, val);

const q = Query.keyExact(key);

console.log("Querying...");
const entries = await doc.getMany(q);

// -----> program never gets here
console.log(`Entries ---- ${entries.length}`);

async function listen() {
  console.log("Subscribing");
  const sub = await doc.subscribe();
  for (const event of sub) {
    const keys = Object.keys(event);
    for (let type of keys) {
      console.log("Event:", type);
      const params = event[type];
      console.log("Data:", params);
    }
  }
}
```

**Comment by ramfox** [comment]
Hi! I'm very grateful that you've been playing around with the node-js api work.

We've been experimenting with this between releases, and have decided to pull this out before the next iroh release. It was meant as a "run up the hill" to see how difficult it would be to get a usable javascript api using ffi bindings.

And I think it's pretty clear from my own investigations and certainly yours as well, that this isn't an api we can translate or maintain in a straightforward way. Our rust apis assume a multithreaded context and we would need some real design work to translate it well to node's single threaded work-stealing assumptions.

Appreciate your effort on this!
