### ISSUE TITLE
Fill in missing command API methods in FFI bindings

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh-ffi#12]
not all methods listed in our [command docs](https://iroh.computer/docs/commands) are present in the uniFFI definition. Not all commands make sense, but let's at least audit all of them & either write FFI bindings, or come up with an approach to get the same behaviour without an actual method.

## Doc Commands
- [x] ~~`doc switch`~~ just use a variable, this is console-specific
- [x] `doc new` - _implemented as `IrohNode.create_doc`_
- [x] `doc join` - _implemented as `IrohNode.import_doc`
- [x] `doc list`
- [x] `doc share` - _implemented as `doc.share_write`_
- [x] `doc set` - _implemented as `doc.set_bytes`_
- [x] `doc get` - _implemeted as `doc.get_content_bytes`_
- [x] `doc keys` - _implemented as `doc.latest`_

## Author Commands
- [x] ~~`author switch`~~ just use a variable, this is console-specific
- [x] `author list`
- [x] `author new` - _implemented as `IrohNode.create_author`_

## Blob Commands
- [x] `blob get`
- [x] `blob add`
- [x] `blob share`
- [x] `blob list blobs`
- [x] `blob list incomplete-blobs`
- [x] `blob list collections`
- [ ] ~`blob validate`~

## Connection Commands
- [x] `node connections`
- [x] `node connection`

**Comment by ramfox** [comment]
closed by #90
