### ISSUE TITLE
Python: Collection.store() and IrohNode.blobs_add_bytes_named() missing

### ISSUE THREAD

**Issue by johnxx** [n0-computer/iroh-ffi#150]
As the title says: I saw those methods referenced in the Rust docs, but I don't see the methods in the Python bindings. They'd be very nice to have. :)

**Comment by johnxx** [comment]
Ah, thanks for the typo-fix. :sweat_smile:
I'll add to the list of missing methods: Doc.get_sync_peers()
And while I'm asking for everything, I'd also really like access to the Rust QueryBuilder from Python rather than having a bunch of separate query methods.

**Comment by dignifiedquire** [comment]
> Collection.store()

This doesn't quite work over ffi, but the function `blobs_create_collection` gives you the ability to store a collection you created, or are you looking for sth else?
