### ISSUE TITLE
Python: Raw Collections header included in Collection.links()

### ISSUE THREAD

**Issue by johnxx** [n0-computer/iroh-ffi#152]
The raw collection header appears to be returned as one of the results by Collection.blobs(). In addition, the blob that was most recently added to the collection *is not* returned. For Collection.links() the raw collection header is returned as the "link" for the first "name" the user attempts to add to the collection. I made a quick repro based on the Python API example:
https://gist.github.com/johnxx/8012a0b65c766c7fef4b0f7514785e1f

I *believe* it's related to the way the collection is retrieved rather than the way it's stored, because interacting with the same collection via the CLI (exporting it recursively) seems to work correctly.

**Comment by dignifiedquire** [comment]
thanks, fix will be in the upcoming `0.20` release
