### ISSUE TITLE
Make clear on published packages which iroh version they are

### ISSUE THREAD

**Issue by flub** [n0-computer/iroh-ffi#32]
Currently the pypi package 0.2.0 is for iroh 0.6.0, but there is no indication whatsoever to the users about this.  We should make it clear in some way what version it refers to.

Some options:

1. Match the version numbers.

   This could be tricky when we need to do new releases in bindings without new iroh releases.

2. Document prominently in the README with a table or similar.

   This would need manual updating and is easy to become stale and make mistakes.

3. ??

**Comment by ramfox** [comment]
We now match the version number to the iroh release number.

But I agree that this is tricky when we need to do releases in ffi without new iroh releases. For now, though, i think it's easiest to just match & bundle all the fixes to the same time iroh does releases.
