### ISSUE TITLE
Bindings laundry list

### ISSUE THREAD

**Issue by Arqu** [n0-computer/iroh-ffi#38]
- [ ] (`python`) doc get bytes example can't be completed because it needs to do `.get_content_bytes` from an entry but `.set_bytes` returns a `Hash` and there is no way to get or construct the matching entry except doing `.keys` and looping over them.
- [ ] no `doc list` support

**Comment by dignifiedquire** [comment]
@Arqu can this be closed

**Comment by Arqu** [comment]
I don't know, havent used ffi in a bit. @ramfox probably knows if this is even relevant any more.

Looking at docs, assuming they are mostly up to date now, the get_content_bytes, while not done via hash now seems to have a convenient way to get by key which is enough for me.
Doc list is present in the docs, by now I assume it's also supported.

I'll close as I'm pretty sure it's done, feel free to reopen tho.
