### ISSUE TITLE
discussion: use `client::Iroh` as a model for the API, rather than the console commands?

### ISSUE THREAD

**Issue by ramfox** [n0-computer/iroh-ffi#48]
we are currently using the commands listed in the [docs](https://iroh.computer/docs/api) as our model for the FFI bindings. But if we want folks to use iroh as a library the way the can use rust, shouldn't we model the API off the methods on the `client::Iroh` struct instead?

**Comment by dignifiedquire** [comment]
yes, that was always my plan

**Comment by dignifiedquire** [comment]
this is now done
