### ISSUE TITLE
Python bindings do not persist secret key

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh-ffi#85]
It seems that python bindings generate a new secret key every time.

![image](https://github.com/n0-computer/iroh/assets/248257/a301b690-fc27-43ce-98aa-c984e948d939)

**Comment by dignifiedquire** [comment]
Moved to iroh-ffi, as we track issues about the bindings here

**Comment by ramfox** [comment]
@ppodolsky this is fixed in the latest release (v0.12.0)!
