### ISSUE TITLE
`Package.swift` is not updated when we cut a new release of `iroh-ffi`

### ISSUE THREAD

**Issue by b5** [n0-computer/iroh-ffi#95]
our [iOS quickstart](https://iroh.computer/docs/examples/ios-starter) leads users to install a swift package dependency, which relies on the root `Package.swift`: https://github.com/n0-computer/iroh-ffi/blob/main/Package.swift

Looks like this file hasn't been updated in 5 months!

Steps to fix:
* [ ] do a "manual upload" to patch the current v0.12.0 release
* [ ] ensure the release is updated on each release, either with documentation that a number 0 engineer can run on each release, or (ideally) a CI script that updates the file

**Comment by warmachinesocial** [comment]
Yes, the example is not working as per the documentation.

**Comment by Arqu** [comment]
This should now be covered for new releases with the release automation scripts in the tools repo

**Comment by Arqu** [comment]
This seems to have worked fine on the latest release.
